export const GET_VIDEO_LESSONS_REQUEST = "GET_VIDEO_LESSONS_REQUEST";
export const GET_VIDEO_LESSONS_SUCCESS = "GET_VIDEO_LESSONS_SUCCESS";
export const GET_VIDEO_LESSONS_FAILURE = "GET_VIDEO_LESSONS_FAILURE";
