import Head from 'next/head'
import ResetScreen from '../../screens/ResetScreen';
import { useRouter } from 'next/router'

export default function Reset() {
	const router = useRouter()
	return (
		<>
			<Head>
				<title>CollegePass - Registration</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<main>
				<ResetScreen
				 GID={router.query.id}
				></ResetScreen>
			</main>
		</>
	)
}
