import Head from 'next/head'
import EventRegistrationScreen from '../../screens/EventRegistrationScreen'
import Reg from '../stanford-martin-walsh'
import CustomRegistration from './ivy-league-townhall'

import { useRouter } from 'next/router'

export default function Registration() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>CollegePass - Registration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="canonical" href="https://www.collegepass.org/about" />
        <meta property="og:url" content="https://www.collegepass.org/terms" />
        <meta property="og:type" content="website" />
        <meta property="og:image" content="https://collegepass.s3.ap-south-1.amazonaws.com/social-media.jpg" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:image" content="https://collegepass.s3.ap-south-1.amazonaws.com/social-media.jpg" />
      </Head>
      <main>
        {router.query.eventID === '87586674175'?<CustomRegistration></CustomRegistration>:
         <EventRegistrationScreen
         eventID={router.query.eventID}
       ></EventRegistrationScreen>}
       
      </main>
    </>
  )
}
