export const liveStreamConstant = 'LIVESTREAM'
export const masterclassCosntant = 'MASTERCLASS'
export const liveClassConstant = 'CLASS'
export const ivyleagueConstant = 'IVY-LEAGUE'
export const oxbridgeConstant = 'OXBRIDGE'
export const liveVideoConstant = 'VIDEO_LESSONS'
export const previousVideoConstant = 'PREV_VIDEO_LESSONS'
