import Head from 'next/head'
import VimeoVideoScreen from '../../../screens/PlaySeriesScreen'
import YoutubeVideoScreen from '../../../screens/PlayVideoScreen/YoutubeScreen'
import { useRouter } from 'next/router'
import Player from '@vimeo/player';
import { useEffect, useState } from 'react';
import axios from 'axios'
import { APIstoreJoinedUser, APIupdateEventSpentTime } from '../../../config/API'
import { useSelector } from 'react-redux'


function PlayVideo() {
  

  const router = useRouter()
  const auth = useSelector((state) => state.auth)

  const [ids, setids] = useState([])
  useEffect(()=>{
    if(router.query.sourcetype && auth.userDetails?.EMAIL !== undefined){
      const ids = router.query.sourcetype?router.query.sourcetype.split('vimeo'):""
    setids(ids)
    
    }
    
  },[router.query.sourcetype, auth.userDetails?.EMAIL])
  

  
  return (
    <>
      <Head>
        <title>CollegePass | Get Into Your Dream Colleg</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <VimeoVideoScreen
            title={router.query.title}
            videoID={router.query.videoID}
            ids={ids}
          ></VimeoVideoScreen>
        
      </main>
    </>
  )
}

export default PlayVideo
