//import React, {Fragment} from 'react'
import Head from 'next/head'
import MyStreamsScreen from '../screens/MySeriesScreen'

// https://api.collegepass.org/api/v1/events/getLiveSession

import axios from 'axios'
import { APIgetMasterClass, APIgetRecordedTypes,getSeries } from '../config/API'

export default function MyStreams({
  series = [],
  recordedLiveStreams = [],
}) {
  // console.log(series)
  return (
    <>
      <Head>
        <title>CollegePass | Get Into Your Dream College</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MyStreamsScreen
          upcomingLiveStreams={series}
          recordedLiveStreams={recordedLiveStreams}
        />
      </main>
    </>
  )
}

export async function getStaticProps() {
  const series = await axios.get(getSeries)
  const recordedLiveStreams = await axios.get(
    `${APIgetRecordedTypes}/masterclass`
  )
  

  return {
    props: {
      series: series.data.message,
      recordedLiveStreams: recordedLiveStreams.data.data,
    }, // will be passed to the page component as props
    revalidate: 5,
  }
}
