//import React, {Fragment} from 'react'
import Head from 'next/head'
import MyStreamsScreen from '../screens/MyOxbridgeScreen'

// https://api.collegepass.org/api/v1/events/getLiveSession

import axios from 'axios'
import { APIgetOxford, APIgetRecordedTypes } from '../config/API'

export default function MyStreams({
  upcomingLiveStreams = [],
  recordedLiveStreams = [],
}) {
  return (
    <>
      <Head>
        <title>CollegePass | Get Into Your Dream College</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MyStreamsScreen
          upcomingLiveStreams={upcomingLiveStreams}
          recordedLiveStreams={recordedLiveStreams}
        />
      </main>
    </>
  )
}

export async function getStaticProps() {
  const upcomingLiveStreams = await axios.get(APIgetOxford)
  const recordedLiveStreams = await axios.get(`${APIgetRecordedTypes}/24`)

  return {
    props: {
      upcomingLiveStreams: upcomingLiveStreams.data.data,
      recordedLiveStreams: recordedLiveStreams.data.data,
    }, // will be passed to the page component as props
    revalidate: 5,
  }
}
