import Head from 'next/head'
import PlanScreen from '../screens/PlanScreen'
import Script from 'next/script'

export default function Plan() {
  return (
    <>
      <Head>
        <title>CollegePass | Get Into Your Dream Colleg</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PlanScreen></PlanScreen>
      </main>

      <footer>
        <Script src="https://checkout.razorpay.com/v1/checkout.js" />
      </footer>
    </>
  )
}
