import Head from 'next/head'
import PromoScreen from '../screens/PromoScreen';

export default function Registration() {
	return (
		<>
			<Head>
				<title>CollegePass - Promo</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<main>
				<PromoScreen></PromoScreen>
			</main>
		</>
	)
}
