import Head from 'next/head'
import PaymentConfirmationScreen from '../../screens/PaymentConfirmationScreen'
import { useRouter } from 'next/router'

export default function Coupon() {
  const router = useRouter()
  const planType = router.query.planType
  return (
    <>
      <Head>
        <title>CollegePass | Get Into Your Dream Colleg</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PaymentConfirmationScreen planType={planType} />
      </main>
      <footer>
        <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
      </footer>
    </>
  )
}
